In [9]:
import numpy as np

# Сигмоїдна активаційна функція та її похідна
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1 - x)


# Вхідні дані
inputs = np.array([[0, 0, 0], [0, 1, 0], [1, 0, 0], [1, 1, 1]])

# Очікувані виходи
expected_output = np.array([[1], [1], [0], [1]])

# Ініціалізація ваг та навчальних параметрів
np.random.seed(1)
weights = np.random.uniform(size=(3, 1))
bias = np.random.uniform(size=(1))
learning_rate = 0.1

# Навчання моделі
for _ in range(10000):
    # Пряме поширення
    hidden_layer_input = np.dot(inputs, weights) + bias
    hidden_layer_output = sigmoid(hidden_layer_input)

    # Розрахунок помилки
    error = expected_output - hidden_layer_output

    # Зворотне поширення
    d_predicted_output = error * sigmoid_derivative(hidden_layer_output)

    # Оновлення ваг та зміщень
    weights += np.dot(inputs.T, d_predicted_output) * learning_rate
    bias += np.sum(d_predicted_output, axis=0) * learning_rate


# Тестування моделі
print("Тестування моделі:")
for i, input_data in enumerate(inputs):
    prediction = sigmoid(np.dot(input_data, weights) + bias)
    print(f"{input_data} -> {prediction}")

print("Ваги та зміщення:")
print(weights)
print(bias)

Тестування моделі:
[0 0 0] -> [0.957989]
[0 1 0] -> [0.99922864]
[1 0 0] -> [0.04185412]
[1 1 1] -> [0.97622774]
Ваги та зміщення:
[[-6.25771457]
 [ 4.03967445]
 [ 2.80631183]]
[3.12690482]
